[package]
name = "notification"
version = "0.1.0"
edition = "2024"

[dependencies]
# Workspace shared dependencies
tokio.workspace = true
axum.workspace = true
tower.workspace = true
tower-http.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
config.workspace = true

# Internal dependencies
common = { path = "../common" }
